<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="localadm-OptiPlex-3020" name="selenium_api.Topic_02_Exercise" tests="5" failures="1" timestamp="7 Nov 2018 02:45:21 GMT" time="47.121" errors="0">
  <testcase name="TC05_CreateAnAccount" time="10.331" classname="selenium_api.Topic_02_Exercise">
    <failure type="java.lang.AssertionError" message="expected [Magento Commerce] but found [Home page]">
      <![CDATA[java.lang.AssertionError: expected [Magento Commerce] but found [Home page]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at selenium_api.Topic_02_Exercise.TC05_CreateAnAccount(Topic_02_Exercise.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- TC05_CreateAnAccount -->
  <testcase name="TC04_LoginWithIncorrectPassword" time="10.473" classname="selenium_api.Topic_02_Exercise"/>
  <testcase name="TC03_LoginWithInvalidEmail" time="8.262" classname="selenium_api.Topic_02_Exercise"/>
  <testcase name="TC01_VerifyUrlAndTitle" time="8.597" classname="selenium_api.Topic_02_Exercise"/>
  <testcase name="TC02_LoginEmpty" time="9.458" classname="selenium_api.Topic_02_Exercise"/>
</testsuite> <!-- selenium_api.Topic_02_Exercise -->
